// Generated by `chimpbase modules sync`; do not edit.

export interface AssetsDatabase {
  "artifact_blobs": Record<string, unknown>;
  "artifact_blobs_v2": Record<string, unknown>;
  "artifacts": Record<string, unknown>;
  "artifacts_v2": Record<string, unknown>;
  "skill_bundles": Record<string, unknown>;
  "skill_revisions": Record<string, unknown>;
  "skill_revisions_v2": Record<string, unknown>;
}

export interface DefinitionsDatabase {
  "active_definition": Record<string, unknown>;
  "agent_profile_revisions": Record<string, unknown>;
  "definition_revisions": Record<string, unknown>;
  "execution_plans": Record<string, unknown>;
  "execution_plans_v2": Record<string, unknown>;
  "execution_plans_v3": Record<string, unknown>;
  "flow_revisions": Record<string, unknown>;
}

export interface EffectsDatabase {
  "effect_bot_correlations_v3": Record<string, unknown>;
  "effect_dry_runs_v3": Record<string, unknown>;
  "effect_intents": Record<string, unknown>;
  "effect_intents_v3": Record<string, unknown>;
  "effect_preconditions": Record<string, unknown>;
  "effect_preconditions_v3": Record<string, unknown>;
  "effect_receipts": Record<string, unknown>;
  "effect_receipts_v3": Record<string, unknown>;
  "effect_reconciliation": Record<string, unknown>;
  "effect_reconciliation_v3": Record<string, unknown>;
}

export interface ExecutionDatabase {
  "attempt_cancellations": Record<string, unknown>;
  "attempt_requests": Record<string, unknown>;
  "attempt_result_metadata": Record<string, unknown>;
  "attempt_results": Record<string, unknown>;
  "step_attempts": Record<string, unknown>;
  "workspace_lifecycle": Record<string, unknown>;
  "workspaces": Record<string, unknown>;
}

export interface IntakeDatabase {
  "delivery_deduplication": Record<string, unknown>;
  "event_sources": Record<string, unknown>;
  "factory_events": Record<string, unknown>;
  "github_comment_snapshots": Record<string, unknown>;
  "github_issue_snapshots": Record<string, unknown>;
  "github_poll_state": Record<string, unknown>;
  "source_cursors": Record<string, unknown>;
  "source_payload_snapshots": Record<string, unknown>;
}

export interface OperationsDatabase {
  "effect_projections": Record<string, unknown>;
  "event_projections": Record<string, unknown>;
  "health_projection": Record<string, unknown>;
  "operator_command_audit": Record<string, unknown>;
  "run_projections": Record<string, unknown>;
  "timeline_projections": Record<string, unknown>;
}

export interface RunsDatabase {
  "operator_commands": Record<string, unknown>;
  "run_admission_slots": Record<string, unknown>;
  "run_admissions": Record<string, unknown>;
  "run_audit": Record<string, unknown>;
  "run_effect_tree_pins": Record<string, unknown>;
  "run_engine_state": Record<string, unknown>;
  "run_execution_pins": Record<string, unknown>;
  "run_gates": Record<string, unknown>;
  "run_identities": Record<string, unknown>;
  "runs": Record<string, unknown>;
  "workflow_signals": Record<string, unknown>;
}

