// Generated by `chimpbase modules sync`; do not edit.

export interface AssetsDatabase {
  "artifacts": Record<string, unknown>;
  "skill_revisions": Record<string, unknown>;
}

export interface DefinitionsDatabase {
  "agent_profile_revisions": Record<string, unknown>;
  "definition_revisions": Record<string, unknown>;
  "execution_plans": Record<string, unknown>;
  "flow_revisions": Record<string, unknown>;
}

export interface EffectsDatabase {
  "effect_intents": Record<string, unknown>;
  "effect_preconditions": Record<string, unknown>;
  "effect_receipts": Record<string, unknown>;
  "effect_reconciliation": Record<string, unknown>;
}

export interface ExecutionDatabase {
  "attempt_results": Record<string, unknown>;
  "step_attempts": Record<string, unknown>;
  "workspaces": Record<string, unknown>;
}

export interface IntakeDatabase {
  "delivery_deduplication": Record<string, unknown>;
  "event_sources": Record<string, unknown>;
  "factory_events": Record<string, unknown>;
  "github_comment_snapshots": Record<string, unknown>;
  "github_issue_snapshots": Record<string, unknown>;
  "github_poll_state": Record<string, unknown>;
  "source_cursors": Record<string, unknown>;
  "source_payload_snapshots": Record<string, unknown>;
}

export interface OperationsDatabase {
  "effect-projections": Record<string, unknown>;
  "event-projections": Record<string, unknown>;
  "run-projections": Record<string, unknown>;
}

export interface RunsDatabase {
  "operator_commands": Record<string, unknown>;
  "run_audit": Record<string, unknown>;
  "run_gates": Record<string, unknown>;
  "run_identities": Record<string, unknown>;
  "runs": Record<string, unknown>;
  "workflow_signals": Record<string, unknown>;
}

