// Generated by `chimpbase modules sync`; do not edit.

export interface AssetsDatabase {
}

export interface DefinitionsDatabase {
}

export interface EffectsDatabase {
}

export interface ExecutionDatabase {
}

export interface IntakeDatabase {
}

export interface OperationsDatabase {
  "effect-projections": Record<string, unknown>;
  "event-projections": Record<string, unknown>;
  "run-projections": Record<string, unknown>;
}

export interface RunsDatabase {
}

