export const CAPABILITY_OWNERS = {
  "agent.run": "agent-runtime",
  "artifact.bytes": "artifact-byte-driver",
  "definition.compile": "definitions",
  "git.publish": "git-publisher",
  "github.read": "github-read-transport",
  "issue.comment": "effects",
  "issue.label": "effects",
  "process.test": "execution",
  "repository.patch": "execution",
  "repository.read": "execution",
  "pull-request.write": "effects",
  "repository.write": "effects",
  "run.coordinate": "runs",
  "source.accept": "intake",
} as const;

export const MODULE_DEPENDENCIES = {
  assets: [],
  definitions: [],
  effects: ["assets", "definitions"],
  execution: ["assets"],
  intake: ["definitions"],
  operations: ["assets", "definitions", "effects", "execution", "intake", "runs"],
  runs: ["assets", "definitions", "effects", "execution", "intake"],
} as const;

export type ModuleName = keyof typeof MODULE_DEPENDENCIES;
export const SQLITE_MODULE_LIMITATIONS = {
  kyselyOwnerEnforcement: false,
  physicalOwnerSchemas: false,
  protection: "generated owner-only database types and trusted-process discipline",
  rawSqlOwnerEnforcement: true,
} as const;

export const MODULE_RESOURCES = {
  assets: {
    collections: ["artifacts", "skill-bundles", "skill-revisions"],
    kvPrefixes: ["artifact-bytes", "artifact-materializations"],
    tables: [
      "artifact_blobs",
      "artifact_blobs_v2",
      "artifacts",
      "artifacts_v2",
      "skill_bundles",
      "skill_revisions",
      "skill_revisions_v2",
    ],
  },
  definitions: {
    collections: [
      "active-definition",
      "agent-profile-revisions",
      "definition-revisions",
      "execution-plans",
      "execution-plans-v2",
      "flow-revisions",
    ],
    tables: [
      "active_definition",
      "agent_profile_revisions",
      "definition_revisions",
      "execution_plans",
      "execution_plans_v2",
      "flow_revisions",
    ],
  },
  effects: {
    collections: [
      "effect-intents",
      "effect-receipts",
      "effect-reconciliation",
      "effect-dry-runs",
      "effect-bot-correlations",
    ],
    queues: ["effect-workers", "effect-workers.dlq"],
    tables: [
      "effect_bot_correlations_v3",
      "effect_dry_runs_v3",
      "effect_intents",
      "effect_intents_v3",
      "effect_preconditions",
      "effect_preconditions_v3",
      "effect_receipts",
      "effect_receipts_v3",
      "effect_reconciliation",
      "effect_reconciliation_v3",
    ],
  },
  execution: {
    collections: ["step-attempts", "workspaces"],
    queues: ["agent-workers"],
    tables: [
      "attempt_requests",
      "attempt_result_metadata",
      "attempt_cancellations",
      "attempt_results",
      "step_attempts",
      "workspace_lifecycle",
      "workspaces",
    ],
  },
  intake: {
    collections: [
      "delivery-deduplication",
      "event-sources",
      "factory-events",
      "github-comment-snapshots",
      "github-issue-snapshots",
      "github-poll-state",
      "source-cursors",
      "source-payload-snapshots",
    ],
    queues: ["github-poll-retries"],
    tables: [
      "delivery_deduplication",
      "event_sources",
      "factory_events",
      "github_comment_snapshots",
      "github_issue_snapshots",
      "github_poll_state",
      "source_cursors",
      "source_payload_snapshots",
    ],
  },
  operations: {
    projections: ["effect-projections", "event-projections", "run-projections"],
  },
  runs: {
    collections: [
      "operator-commands",
      "run-admissions",
      "run-admission-slots",
      "run-engine-state",
      "run-gates",
      "runs",
      "workflow-signals",
    ],
    tables: [
      "operator_commands",
      "run_admission_slots",
      "run_execution_pins",
      "run_admissions",
      "run_audit",
      "run_engine_state",
      "run_gates",
      "run_identities",
      "runs",
      "workflow_signals",
    ],
    workflows: ["factory-runs", "factory-runs-v2"],
  },
} as const;

export const RESOURCE_OWNERS = {
  "active-definition": "definitions",
  active_definition: "definitions",
  "agent-profile-revisions": "definitions",
  agent_profile_revisions: "definitions",
  "agent-workers": "execution",
  "artifact-bytes": "assets",
  "artifact-materializations": "assets",
  artifacts: "assets",
  artifacts_v2: "assets",
  attempt_requests: "execution",
  attempt_cancellations: "execution",
  artifact_blobs: "assets",
  artifact_blobs_v2: "assets",
  skill_revisions_v2: "assets",
  attempt_result_metadata: "execution",
  attempt_results: "execution",
  definition_revisions: "definitions",
  "definition-revisions": "definitions",
  "delivery-deduplication": "intake",
  delivery_deduplication: "intake",
  effect_intents: "effects",
  effect_bot_correlations_v3: "effects",
  "effect-bot-correlations": "effects",
  effect_dry_runs_v3: "effects",
  "effect-dry-runs": "effects",
  effect_intents_v3: "effects",
  effect_preconditions_v3: "effects",
  effect_preconditions: "effects",
  "effect-projections": "operations",
  "effect-intents": "effects",
  effect_receipts: "effects",
  effect_reconciliation: "effects",
  effect_receipts_v3: "effects",
  effect_reconciliation_v3: "effects",
  "effect-workers.dlq": "effects",
  "effect-workers": "effects",
  "effect-receipts": "effects",
  "effect-reconciliation": "effects",
  "event-delivery": "chimpbase",
  "event:ArtifactStored.v1": "assets",
  "event:ArtifactStored.v2": "assets",
  "event:AttemptFinished.v1": "execution",
  "event:AttemptFinished.v2": "execution",
  "event:AttemptQueued.v1": "execution",
  "event:AttemptQueued.v2": "execution",
  "event:AttemptQueued.v3": "execution",
  "event:DefinitionPublished.v1": "definitions",
  "event:EffectFinished.v1": "effects",
  "event:EffectFinished.v3": "effects",
  "event:EffectQueued.v2": "effects",
  "event:EffectFinished.v2": "effects",
  "event:EffectQueued.v1": "effects",
  "event:EffectRequested.v1": "runs",
  "event:EffectRequested.v2": "runs",
  "event:EffectRequested.v3": "runs",
  "event:FactoryEventAccepted.v1": "intake",
  "event:FactoryEventAccepted.v2": "intake",
  "event:RunFinished.v1": "runs",
  "event:RunFinished.v3": "runs",
  "event:RunFinished.v2": "runs",
  "event:RunStateChanged.v1": "runs",
  "event:RunStateChanged.v2": "runs",
  "event:RunStateChanged.v3": "runs",
  "event:SkillRevisionPinned.v1": "assets",
  "event:SkillRevisionPinned.v2": "assets",
  "event:StepRequested.v1": "runs",
  "event:StepRequested.v2": "runs",
  "event-projections": "operations",
  "event-sources": "intake",
  event_sources: "intake",
  "execution-plans": "definitions",
  "execution-plans-v2": "definitions",
  execution_plans_v2: "definitions",
  execution_plans: "definitions",
  "factory-events": "intake",
  factory_events: "intake",
  github_comment_snapshots: "intake",
  "github-comment-snapshots": "intake",
  github_issue_snapshots: "intake",
  "github-issue-snapshots": "intake",
  github_poll_state: "intake",
  "github-poll-retries": "intake",
  "github-poll-state": "intake",
  "factory-runs-v2": "runs",
  "factory-runs": "runs",
  "flow-revisions": "definitions",
  flow_revisions: "definitions",
  "health-routes": "operations",
  "module-manifest": "chimpbase",
  namespaces: "chimpbase",
  operator_commands: "runs",
  "operator-commands": "runs",
  "operator-routes": "operations",
  "repository-poll-crons": "intake",
  "run-admission-slots": "runs",
  run_admission_slots: "runs",
  "run-admissions": "runs",
  run_admissions: "runs",
  run_audit: "runs",
  run_gates: "runs",
  run_identities: "runs",
  "run-engine-state": "runs",
  run_execution_pins: "runs",
  run_engine_state: "runs",
  "run-gates": "runs",
  "run-projections": "operations",
  runs: "runs",
  skill_revisions: "assets",
  "skill-revisions": "assets",
  source_cursors: "intake",
  "source-cursors": "intake",
  "source-payload-snapshots": "intake",
  source_payload_snapshots: "intake",
  step_attempts: "execution",
  telemetry: "chimpbase",
  "skill-bundles": "assets",
  skill_bundles: "assets",
  "step-attempts": "execution",
  "workflow-engine": "chimpbase",
  workflow_signals: "runs",
  "workflow-signals": "runs",
  workspace_lifecycle: "execution",
  workspaces: "execution",
} as const;
