export const CAPABILITY_OWNERS = {
  "agent.execute": "agent-runtime",
  "artifact.bytes": "artifact-byte-driver",
  "definition.compile": "definitions",
  "git.publish": "git-publisher",
  "github.transport": "github-transport",
  "issue.comment": "effects",
  "repository.read": "execution",
  "repository.write": "effects",
  "run.coordinate": "runs",
  "source.accept": "intake",
} as const;

export const MODULE_DEPENDENCIES = {
  assets: [],
  definitions: [],
  effects: ["assets", "definitions"],
  execution: ["assets"],
  intake: ["definitions"],
  operations: ["assets", "definitions", "effects", "execution", "intake", "runs"],
  runs: ["assets", "definitions", "effects", "execution"],
} as const;

export type ModuleName = keyof typeof MODULE_DEPENDENCIES;
export const SQLITE_MODULE_LIMITATIONS = {
  kyselyOwnerEnforcement: false,
  physicalOwnerSchemas: false,
  protection: "generated owner-only database types and trusted-process discipline",
  rawSqlOwnerEnforcement: true,
} as const;

export const MODULE_RESOURCES = {
  assets: {
    collections: ["artifacts", "skill-revisions"],
    kvPrefixes: ["artifact-bytes", "artifact-materializations"],
    tables: ["artifacts", "skill_revisions"],
  },
  definitions: {
    collections: [
      "agent-profile-revisions",
      "definition-revisions",
      "execution-plans",
      "flow-revisions",
    ],
    tables: [
      "agent_profile_revisions",
      "definition_revisions",
      "execution_plans",
      "flow_revisions",
    ],
  },
  effects: {
    collections: ["effect-intents", "effect-receipts", "effect-reconciliation"],
    queues: ["effect-workers"],
    tables: ["effect_intents", "effect_preconditions", "effect_receipts", "effect_reconciliation"],
  },
  execution: {
    collections: ["step-attempts", "workspaces"],
    queues: ["agent-workers"],
    tables: ["attempt_results", "step_attempts", "workspaces"],
  },
  intake: {
    collections: [
      "delivery-deduplication",
      "event-sources",
      "factory-events",
      "source-cursors",
      "source-payload-snapshots",
    ],
    tables: [
      "delivery_deduplication",
      "event_sources",
      "factory_events",
      "source_cursors",
      "source_payload_snapshots",
    ],
  },
  operations: {
    projections: ["effect-projections", "event-projections", "run-projections"],
  },
  runs: {
    collections: ["operator-commands", "run-gates", "runs", "workflow-signals"],
    tables: [
      "operator_commands",
      "run_audit",
      "run_gates",
      "run_identities",
      "runs",
      "workflow_signals",
    ],
    workflows: ["factory-runs"],
  },
} as const;

export const RESOURCE_OWNERS = {
  "agent-profile-revisions": "definitions",
  agent_profile_revisions: "definitions",
  "agent-workers": "execution",
  "artifact-bytes": "assets",
  "artifact-materializations": "assets",
  artifacts: "assets",
  attempt_results: "execution",
  definition_revisions: "definitions",
  "definition-revisions": "definitions",
  "delivery-deduplication": "intake",
  delivery_deduplication: "intake",
  effect_intents: "effects",
  effect_preconditions: "effects",
  "effect-projections": "operations",
  "effect-intents": "effects",
  effect_receipts: "effects",
  effect_reconciliation: "effects",
  "effect-workers": "effects",
  "effect-receipts": "effects",
  "effect-reconciliation": "effects",
  "event-delivery": "chimpbase",
  "event:ArtifactStored.v1": "assets",
  "event:AttemptFinished.v1": "execution",
  "event:AttemptQueued.v1": "execution",
  "event:DefinitionPublished.v1": "definitions",
  "event:EffectFinished.v1": "effects",
  "event:EffectFinished.v2": "effects",
  "event:EffectQueued.v1": "effects",
  "event:EffectRequested.v1": "runs",
  "event:EffectRequested.v2": "runs",
  "event:FactoryEventAccepted.v1": "intake",
  "event:FactoryEventAccepted.v2": "intake",
  "event:RunFinished.v1": "runs",
  "event:RunFinished.v2": "runs",
  "event:RunStateChanged.v1": "runs",
  "event:RunStateChanged.v2": "runs",
  "event:SkillRevisionPinned.v1": "assets",
  "event:StepRequested.v1": "runs",
  "event-projections": "operations",
  "event-sources": "intake",
  event_sources: "intake",
  "execution-plans": "definitions",
  execution_plans: "definitions",
  "factory-events": "intake",
  factory_events: "intake",
  "factory-runs": "runs",
  "flow-revisions": "definitions",
  flow_revisions: "definitions",
  "health-routes": "operations",
  "module-manifest": "chimpbase",
  namespaces: "chimpbase",
  operator_commands: "runs",
  "operator-commands": "runs",
  "operator-routes": "operations",
  "repository-poll-crons": "intake",
  run_audit: "runs",
  run_gates: "runs",
  run_identities: "runs",
  "run-gates": "runs",
  "run-projections": "operations",
  runs: "runs",
  skill_revisions: "assets",
  "skill-revisions": "assets",
  source_cursors: "intake",
  "source-cursors": "intake",
  "source-payload-snapshots": "intake",
  source_payload_snapshots: "intake",
  step_attempts: "execution",
  telemetry: "chimpbase",
  "step-attempts": "execution",
  "workflow-engine": "chimpbase",
  workflow_signals: "runs",
  "workflow-signals": "runs",
  workspaces: "execution",
} as const;
